### ISSUE TITLE
Runaway "cvs -Q update -C -p" operations

### ISSUE THREAD

**Issue by mtc900** [Schwartzkers/cvs-scm#5]
Running on latest vscode on macOS the "cvs -Q update -C -p" operation frequently chews up 100% of the cpu. Many times there are multiple of these, some also using significant CPU. I tried disabling the extension but it still generated new cvs operations. 

Let me know what additional information you may need. Thanks!

**Comment by Schwartzkers** [comment]
Thanks for making me aware of the issue. The code in question is definitely not optimized and needs improvements. I had planned to revisit this area but since it had not been causing me too much grief with my large projects/files I dropped it in priority.

The good news is that I think I have some improvements that may help. I develop on Ubuntu so I cannot be completely sure it will fix all your issues. There will continue to be a cpu hit from  vscode to load the quick diff when you view changes. But the excessive "cvs -Q update -C -p" operations should be gone now.  

Version 1.6.1 should be released within the next 48 hrs with the improvements.

**Comment by mtc900** [comment]
I pulled 1.6.1 earlier this afternoon and it has been working flawlessly! Thanks for the super fast response.

**Comment by Schwartzkers** [comment]
Goad to hear the extension is now working for you. Thank you for raising the issue and confirming the fix.
